# Importing Necessary Modules

In [89]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Reading Data

In [90]:
df=pd.read_csv(r"C:\Users\SOOSAN SHABNAM\OneDrive\Desktop\CSI HACK\all_matches.csv")
pd.set_option('display.max_columns', None)
df.head()

c:\users\soosan shabnam\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,0,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Understanding Data

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208042 entries, 0 to 208041
Data columns (total 22 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   match_id                208042 non-null  int64
 1   season                  208042 non-null  object
 2   start_date              208042 non-null  object
 3   venue                   208042 non-null  object
 4   innings                 208042 non-null  int64
 5   ball                    208042 non-null  float64
 6   batting_team            208042 non-null  object
 7   bowling_team            208042 non-null  object
 8   striker                 208042 non-null  object
 9   non_striker             208042 non-null  object
 10  bowler                  208042 non-null  object
 11  runs_off_bat            208042 non-null  int64
 12  extras                  208042 non-null  int64
 13  wides                   6324 non-null    float64
 14  noballs                 846 non-null     float64
 15  byes                    547 non-null     float64
 16  legbyes                 3288 non-null    float64
 17  penalty                 2 non-null       float64
 18  wicket_type             10239 non-null   object
 19  player_dismissed        10239 non-null   object
 20  other_wicket_type       0 non-null       float64
 21  other_player_dismissed  0 non-null       float64
dtypes: float64(8), int64(4), object(10)
memory usage: 34.9+ MB

In [92]:
df.describe()

,match_id,innings,ball,runs_off_bat,extras,wides,noballs,byes,legbyes,penalty,other_wicket_type,other_player_dismissed
count,2.080420e+05,208042.000000,208042.000000,208042.000000,208042.000000,6324.000000,846.000000,547.000000,3288.000000,2.0,0.0,0.0
mean,7.913677e+05,1.483744,9.538335,1.239783,0.066213,1.203985,1.041371,1.829982,1.298358,5.0,NaN,NaN
std,3.212030e+05,0.503388,5.682836,1.610708,0.338622,0.783636,0.356764,1.291837,0.837280,0.0,NaN,NaN
min,3.359820e+05,1.000000,0.100000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,5.0,NaN,NaN
25%,5.012420e+05,1.000000,4.500000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,5.0,NaN,NaN
50%,7.340090e+05,1.000000,9.400000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,5.0,NaN,NaN
75%,1.136584e+06,2.000000,14.400000,1.000000,0.000000,1.000000,1.000000,4.000000,1.000000,5.0,NaN,NaN
max,1.254117e+06,6.000000,19.900000,6.000000,7.000000,5.000000,5.000000,4.000000,5.000000,5.0,NaN,NaN

In [93]:
df['other_wicket_type'].unique()

array([nan])

In [94]:
df['other_player_dismissed'].unique()

array([nan])

In [95]:
df[df['wides'] == 1.0]

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
2,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,12.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,DJ Hussey,JH Kallis,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,2,0.2,Royal Challengers Bangalore,Kolkata Knight Riders,W Jaffer,R Dravid,AB Dinda,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,2,2.5,Royal Challengers Bangalore,Kolkata Knight Riders,W Jaffer,JH Kallis,AB Dinda,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,2,6.4,Royal Challengers Bangalore,Kolkata Knight Riders,MV Boucher,CL White,AB Agarkar,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207984,1254117,2021,2021-10-15,Dubai International Cricket Stadium,2,11.3,Kolkata Knight Riders,Chennai Super Kings,SP Narine,Shubman Gill,JR Hazlewood,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208006,1254117,2021,2021-10-15,Dubai International Cricket Stadium,2,14.6,Kolkata Knight Riders,Chennai Super Kings,Shakib Al Hasan,EJG Morgan,RA Jadeja,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208027,1254117,2021,2021-10-15,Dubai International Cricket Stadium,2,18.2,Kolkata Knight Riders,Chennai Super Kings,Shivam Mavi,LH Ferguson,SN Thakur,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208031,1254117,2021,2021-10-15,Dubai International Cricket Stadium,2,18.6,Kolkata Knight Riders,Chennai Super Kings,LH Ferguson,Shivam Mavi,SN Thakur,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208032,1254117,2021,2021-10-15,Dubai International Cricket Stadium,2,18.7,Kolkata Knight Riders,Chennai Super Kings,LH Ferguson,Shivam Mavi,SN Thakur,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
df['wicket_type'].unique()

array([nan, 'caught', 'bowled', 'run out', 'lbw', 'retired hurt',
       'stumped', 'caught and bowled', 'hit wicket',
       'obstructing the field'], dtype=object)

In [97]:
df['player_dismissed'].unique()

array([nan, 'SC Ganguly', 'RT Ponting', 'DJ Hussey', 'R Dravid',
       'V Kohli', 'JH Kallis', 'W Jaffer', 'MV Boucher', 'B Akhil',
       'CL White', 'AA Noffke', 'Z Khan', 'SB Joshi', 'PA Patel',
       'ML Hayden', 'MS Dhoni', 'SK Raina', 'JDP Oram', 'K Goel',
       'JR Hopes', 'Yuvraj Singh', 'KC Sangakkara', 'T Kohli',
       'YK Pathan', 'SR Watson', 'DS Lehmann', 'M Kaif', 'M Rawat',
       'RA Jadeja', 'SK Warne', 'V Sehwag', 'Y Venugopal Rao',
       'VVS Laxman', 'AC Gilchrist', 'RG Sharma', 'SB Styris', 'AS Yadav',
       'A Symonds', 'WPUJC Vaas', 'SB Bangar', 'PP Ojha', 'BB McCullum',
       'WP Saha', 'Mohammad Hafeez', 'L Ronchi', 'DJ Thornely',
       'ST Jayasuriya', 'PR Shah', 'RV Uthappa', 'AM Nayar', 'SM Pollock',
       'S Chanderpaul', 'LRPL Taylor', 'DPMD Jayawardene', 'IK Pathan',
       'B Lee', 'S Sohal', 'Kamran Akmal', 'Shahid Afridi', 'G Gambhir',
       'MEK Hussey', 'DJ Bravo', 'MA Khote', 'Harbhajan Singh',
       'GC Smith', 'D Salunkhe', 'RR Sarwan', 'PP Chawla', 'S Sreesanth',
       'VRV Singh', 'SS Tiwary', 'AB Agarkar', 'M Kartik', 'LR Shukla',
       'P Kumar', 'AM Rahane', 'S Dhawan', 'Shoaib Malik', 'KD Karthik',
       'R Bhatia', 'MK Tiwary', 'MF Maharoof', 'SM Katich',
       'TM Srivastava', 'B Chipli', 'DW Steyn', 'DB Das', 'MK Pandey',
       'SA Asnodkar', 'Salman Butt', 'BJ Hodge', 'Umar Gul', 'AB Dinda',
       'HH Gibbs', 'DNT Zoysa', 'D Kalyankrishna', 'SP Fleming',
       'S Vidyut', 'JA Morkel', 'SE Marsh', 'Misbah-ul-Haq',
       'S Badrinath', 'Joginder Sharma', 'M Muralitharan', 'M Ntini',
       'YV Takawale', 'AB de Villiers', 'PJ Sangwan', 'Mohammad Asif',
       'GD McGrath', 'DT Patil', 'A Kumble', 'S Anirudha',
       'Sohail Tanvir', 'SK Trivedi', 'CK Kapugedera', 'A Chopra',
       'T Taibu', 'J Arunkumar', 'DB Ravi Teja', 'RP Singh', 'A Mishra',
       'AD Mascarenhas', 'R Vinay Kumar', 'TM Dilshan', 'VY Mahesh',
       'SR Tendulkar', 'I Sharma', 'Shoaib Akhtar', 'LPC Silva', 'H Das',
       'SP Goswami', 'DR Smith', 'SD Chitnis', 'A Nehra', 'VS Yeligati',
       'MS Gony', 'L Balaji', 'LA Pomersbach', 'A Nel', 'A Mukund',
       'Younis Khan', 'Niraj Patel', 'WA Mota', 'JD Ryder',
       'KP Pietersen', 'T Henderson', 'MM Patel', 'Kamran Khan',
       'JP Duminy', 'A Flintoff', 'RS Bopara', 'CH Gayle', 'MC Henriques',
       'R Bishnoi', 'KV Sharma', 'PC Valthaty', 'RJ Quiney',
       'Yashpal Singh', 'Pankaj Singh', 'FH Edwards', 'AS Raut',
       'AN Ghosh', 'BAW Mendis', 'DL Vettori', 'RE van der Merwe',
       'RR Powar', 'AA Bilakhia', 'TL Suman', 'Shoaib Ahmed', 'GR Napier',
       'MN van Wyk', 'M Vijay', 'SB Jakati', 'DA Warner', 'M Manhas',
       'NV Ojha', 'LA Carseldine', 'RJ Harris', 'D du Preez', 'RR Raje',
       'DS Kulkarni', 'M Morkel', 'AD Mathews', 'C Nanda', 'SL Malinga',
       'S Tyagi', 'J Botha', 'A Singh', 'GJ Bailey', 'AB McDonald',
       'Y Nagar', 'SS Shaikh', 'R Ashwin', 'T Thushara',
       'Mohammad Ashraful', 'CA Pujara', 'Anirudh Singh', 'MS Bisla',
       'AP Tare', 'AT Rayudu', 'R Sathish', 'AA Jhunjhunwala', 'P Dogra',
       'A Uniyal', 'JM Kemp', 'EJG Morgan', 'OA Shah', 'RS Gavaskar',
       'SE Bond', 'KA Pollard', 'DP Nannes', 'MJ Lumb', 'DR Martyn',
       'S Narwal', 'AB Barath', 'FY Fazal', 'MD Mishra', 'S Ladda',
       'J Theron', 'SJ Srivastava', 'R Sharma', 'Mandeep Singh',
       'AC Voges', 'Jaskaran Singh', 'KAJ Roach', 'PD Collingwood',
       'CK Langeveldt', 'VS Malik', 'KM Jadhav', 'SW Tait', 'A Mithun',
       'AP Dole', 'Harmeet Singh', 'R McLaren', 'S Sriram', 'KP Appanna',
       'C Madan', 'AG Paunikar', 'MR Marsh', 'AJ Finch', 'STR Binny',
       'B Sumanth', 'IR Jaggi', 'DT Christian', 'RV Gomez', 'MA Agarwal',
       'Sunny Singh', 'UBT Chand', 'UT Yadav', 'DJ Jacobs', 'AL Menaria',
       'AUK Pathan', 'WD Parnell', 'JJ van der Wath', 'R Ninan',
       'MS Wade', 'TD Paine', 'SB Wagh', 'JEC Franklin',
       'Shakib Al Hasan', 'BJ Haddin', 'S Randiv', 'NLTC Perera',
       'JE Taylor', 'NL McCullum', 'RN ten Doeschate', 'TR Birt',
       'M Klinger', 'Harpreet Singh', 'Bipul Sharma', 'AC Blizzard',
       'CA Ingram', 'S Nadeem', 'DH Yagnik', 'KB Arun Karthik',
       'AA Chavan', 'ND Doshi', 'CJ Ferguson', 'Y Gnaneswara Rao',
       'S Rana', 'BA Bhatt', 'F du Plessis', 'DE Bollinger', 'RE Levi',
       'MN Samuels', 'B Kumar', 'SPD Smith', 'SA Yadav', 'DJ Harris',
       'Ankit Sharma', 'HV Patel', 'GJ Maxwell', 'JP Faulkner',
       'SP Narine', 'KK Cooper', 'GB Hogg', 'RR Bhatkal', 'CJ McKay',
       'N Saini', 'DA Miller', 'P Negi', 'Azhar Mahmood', 'AC Thomas',
       'RJ Peterson', 'A Ashish Reddy', 'V Pratap Singh', 'MJ Clarke',
       'Gurkeerat Singh', 'VR Aaron', 'PA Reddy', 'AP Majumdar',
       'AD Russell', 'CA Lynn', 'Sunny Gupta', 'MC Juneja', 'KK Nair',
       'GH Vihari', 'MDKJ Perera', 'B Laughlin', 'Mohammed Shami',
       'BMAJ Mendis', 'M Vohra', 'R Rampaul', 'P Awana',
       'SMSM Senanayake', 'BJ Rohrer', 'KL Rahul', 'J Syed Mohammad',
       'Q de Kock', 'BB Samantray', 'R Dhawan', 'MG Johnson', 'LJ Wright',
       'AG Murtaza', 'IC Pandey', 'X Thalaivan Sargunam', 'DJG Sammy',
       'SV Samson', 'KW Richardson', 'CH Morris', 'MM Sharma',
       'CM Gautam', 'UA Birla', 'Parvez Rasool', 'Sachin Baby',
       'NM Coulter-Nile', 'CJ Anderson', 'NJ Maddinson', 'AR Patel',
       'JDS Neesham', 'TG Southee', 'PV Tambe', 'MA Starc', 'BR Dunk',
       'RR Rossouw', 'Shivam Sharma', 'LMP Simmons', 'VH Zol',
       'BCJ Cutting', 'Imran Tahir', 'R Shukla', 'BE Hendricks',
       'M de Lange', 'S Gopal', 'R Tewatia', 'JO Holder', 'JD Unadkat',
       'Iqbal Abdulla', 'SS Iyer', 'DJ Hooda', 'SN Khan', 'D Wiese',
       'HH Pandya', 'MJ McClenaghan', 'SA Abbott', 'AN Ahmed',
       'KS Williamson', 'Anureet Singh', 'DJ Muthuswami', 'PJ Cummins',
       'Karanveer Singh', 'Sandeep Sharma', 'J Suchith', 'JC Buttler',
       'CR Brathwaite', 'MP Stoinis', 'Ishan Kishan', 'C Munro',
       'AD Nath', 'MJ Guptill', 'P Sahu', 'TM Head', 'M Ashwin',
       'KH Pandya', 'NS Naik', 'RR Pant', 'SW Billings', 'KC Cariappa',
       'PSP Handscomb', 'Swapnil Singh', 'J Yadav', 'UT Khawaja',
       'HM Amla', 'JJ Bumrah', 'A Zampa', 'N Rana', 'S Kaushik',
       'F Behardien', 'KJ Abbott', 'ER Dwivedi', 'CJ Jordan', 'S Aravind',
       'TS Mills', 'YS Chahal', 'BA Stokes', 'JJ Roy', 'Vishnu Vinod',
       'CR Woakes', 'RA Tripathi', 'DL Chahar', 'V Shankar',
       'Rashid Khan', 'SN Thakur', 'C de Grandhomme', 'S Badree',
       'AF Milne', 'Mohammad Nabi', 'K Rabada', 'AJ Tye', 'Kuldeep Yadav',
       'SP Jackson', 'Ankit Soni', 'A Choudhary', 'AS Rajpoot',
       'Washington Sundar', 'MM Ali', 'SO Hetmyer', 'S Dube', 'NA Saini',
       'JM Bairstow', 'PP Shaw', 'KMA Paul', 'N Pooran', 'JC Archer',
       'K Gowtham', 'M Markande', 'Shubman Gill', 'P Ray Barman',
       'SM Curran', 'GC Viljoen', 'S Lamichhane', 'RD Chahar', 'S Kaul',
       'Mohammed Siraj', 'M Prasidh Krishna', 'SD Lad', 'R Parag',
       'JL Denly', 'LS Livingstone', 'RK Bhui', 'Abhishek Sharma',
       'KK Ahmed', 'AJ Turner', 'E Lewis', 'MA Wood', 'RK Singh',
       'DJM Short', 'Mujeeb Ur Rahman', 'Shivam Mavi', 'TK Curran',
       'TA Boult', 'H Klaasen', 'LE Plunkett', 'Basil Thampi',
       'Mustafizur Rahman', 'BB Sran', 'AD Hales', 'MK Lomror',
       'DR Shorey', 'P Chopra', 'IS Sodhi', 'JPR Scantlebury-Searles',
       'SE Rutherford', 'MJ Santner', 'P Simran Singh', 'JL Pattinson',
       'D Padikkal', 'PK Garg', 'YBK Jaiswal', 'RD Gaikwad',
       'JR Philippe', 'Ravi Bishnoi', 'Abdul Samad', 'I Udana',
       'KL Nagarkoti', 'CV Varun', 'SS Cottrell', 'Arshdeep Singh',
       'N Jagadeesan', 'T Banton', 'AT Carey', 'TU Deshpande', 'A Nortje',
       'Kartik Tyagi', 'DR Sams', 'M Jansen', 'RM Patidar',
       'Shahbaz Ahmed', 'KA Jamieson', 'JA Richardson', 'Lalit Yadav',
       'M Shahrukh Khan', 'Virat Singh', 'FA Allen', 'C Sakariya',
       'DJ Malan', 'Anmolpreet Singh', 'KS Bharat', 'PWH de Silva',
       'VR Iyer', 'TH David', 'AK Markram', 'NT Ellis', 'Avesh Khan',
       'TL Seifert', 'GHS Garton', 'RV Patel', 'GD Phillips',
       'Anuj Rawat'], dtype=object)

# Cleaning Data

In [98]:
df=df.drop(['other_wicket_type','other_player_dismissed', 'penalty'],axis=1)
df.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wides,noballs,byes,legbyes,wicket_type,player_dismissed
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,0,1,NaN,NaN,NaN,1.0,NaN,NaN
1,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,1,1.0,NaN,NaN,NaN,NaN,NaN
3,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
df['season'].unique()

array(['2007/08', '2009', '2009/10', '2011', '2012', 2012, 2013, 2014,
       2015, 2016, 2017, 2019, 2018, '2018', '2019', '2020/21', '2021',
       2021], dtype=object)

In [100]:
df['season'] = df['season'].replace(['2007/08', '2009', '2009/10', '2011', '2012', '2018', '2019', '2021/21', '2021'], [2008, 2009, 2010, 2011, 2012, 2018, 2019, 2020, 2021])

In [101]:
df['season'].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2019,
       2018, '2020/21', 2021], dtype=object)

In [106]:
df['season'] = df['season'].replace(['2020/21'], 2020)

# After Cleaning

In [107]:
df.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wides,noballs,byes,legbyes,wicket_type,player_dismissed
0,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,0,1,NaN,NaN,NaN,1.0,NaN,NaN
1,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,1,1.0,NaN,NaN,NaN,NaN,NaN
3,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [108]:
seasons = df['season'].unique()
match_ids = df['match_id'].unique()

In [105]:
np.sort(seasons)

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021], dtype=int64)

In [109]:
df['innings'].unique()

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [110]:
team_metric = pd.DataFrame(columns=['match_id','season','venue','batting_team','total_score','wickets','end_over','arr'])

In [111]:
df['match_id'][0]

335982

In [112]:
super_over=pd.DataFrame(columns=['match_id','season','start_date', 'venue','innings', 'ball','batting_team','bowling_team','striker','non_striker','bowler','runs_off_bat','extras','wides','noballs','byes','legbyes','wicket_type','player_dismissed'])
super_over=df.loc[(df['innings']==3) | (df['innings']==4) | (df['innings']==5) | (df['innings']==6 )]
super_over

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wides,noballs,byes,legbyes,wicket_type,player_dismissed
15417,392190,2009,2009-04-23,Newlands,3,0.1,Kolkata Knight Riders,Rajasthan Royals,CH Gayle,BB McCullum,Kamran Khan,1,0,NaN,NaN,NaN,NaN,NaN,NaN
15418,392190,2009,2009-04-23,Newlands,3,0.2,Kolkata Knight Riders,Rajasthan Royals,BB McCullum,CH Gayle,Kamran Khan,1,0,NaN,NaN,NaN,NaN,NaN,NaN
15419,392190,2009,2009-04-23,Newlands,3,0.3,Kolkata Knight Riders,Rajasthan Royals,CH Gayle,BB McCullum,Kamran Khan,0,1,1.0,NaN,NaN,NaN,NaN,NaN
15420,392190,2009,2009-04-23,Newlands,3,0.4,Kolkata Knight Riders,Rajasthan Royals,CH Gayle,BB McCullum,Kamran Khan,4,0,NaN,NaN,NaN,NaN,NaN,NaN
15421,392190,2009,2009-04-23,Newlands,3,0.5,Kolkata Knight Riders,Rajasthan Royals,CH Gayle,BB McCullum,Kamran Khan,4,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198500,1254077,2021,2021-04-25,"MA Chidambaram Stadium, Chepauk, Chennai",4,0.2,Delhi Capitals,Sunrisers Hyderabad,S Dhawan,RR Pant,Rashid Khan,0,1,NaN,NaN,NaN,1.0,NaN,NaN
198501,1254077,2021,2021-04-25,"MA Chidambaram Stadium, Chepauk, Chennai",4,0.3,Delhi Capitals,Sunrisers Hyderabad,RR Pant,S Dhawan,Rashid Khan,4,0,NaN,NaN,NaN,NaN,NaN,NaN
198502,1254077,2021,2021-04-25,"MA Chidambaram Stadium, Chepauk, Chennai",4,0.4,Delhi Capitals,Sunrisers Hyderabad,RR Pant,S Dhawan,Rashid Khan,0,0,NaN,NaN,NaN,NaN,NaN,NaN
198503,1254077,2021,2021-04-25,"MA Chidambaram Stadium, Chepauk, Chennai",4,0.5,Delhi Capitals,Sunrisers Hyderabad,RR Pant,S Dhawan,Rashid Khan,0,1,NaN,NaN,NaN,1.0,NaN,NaN
198504,1254077,2021,2021-04-25,"MA Chidambaram Stadium, Chepauk, Chennai",4,0.6,Delhi Capitals,Sunrisers Hyderabad,S Dhawan,RR Pant,Rashid Khan,0,1,NaN,NaN,NaN,1.0,NaN,NaN

In [118]:
df_filtered = df[(df['innings'] == 1) | (df['innings'] == 2)]
df_filtered

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wides,noballs,byes,legbyes,wicket_type,player_dismissed
0,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,0,1,NaN,NaN,NaN,1.0,NaN,NaN
1,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,1,1.0,NaN,NaN,NaN,NaN,NaN
3,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208037,1254117,2021,2021-10-15,Dubai International Cricket Stadium,2,19.2,Kolkata Knight Riders,Chennai Super Kings,Shivam Mavi,LH Ferguson,DJ Bravo,1,0,NaN,NaN,NaN,NaN,NaN,NaN
208038,1254117,2021,2021-10-15,Dubai International Cricket Stadium,2,19.3,Kolkata Knight Riders,Chennai Super Kings,LH Ferguson,Shivam Mavi,DJ Bravo,1,0,NaN,NaN,NaN,NaN,NaN,NaN
208039,1254117,2021,2021-10-15,Dubai International Cricket Stadium,2,19.4,Kolkata Knight Riders,Chennai Super Kings,Shivam Mavi,LH Ferguson,DJ Bravo,0,0,NaN,NaN,NaN,NaN,NaN,NaN
208040,1254117,2021,2021-10-15,Dubai International Cricket Stadium,2,19.5,Kolkata Knight Riders,Chennai Super Kings,Shivam Mavi,LH Ferguson,DJ Bravo,0,0,NaN,NaN,NaN,NaN,caught,Shivam Mavi
208041,1254117,2021,2021-10-15,Dubai International Cricket Stadium,2,19.6,Kolkata Knight Riders,Chennai Super Kings,LH Ferguson,CV Varun,DJ Bravo,1,0,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 207881 entries, 0 to 208041
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          207881 non-null  int64
 1   season            207881 non-null  int64
 2   start_date        207881 non-null  object
 3   venue             207881 non-null  object
 4   innings           207881 non-null  int64
 5   ball              207881 non-null  float64
 6   batting_team      207881 non-null  object
 7   bowling_team      207881 non-null  object
 8   striker           207881 non-null  object
 9   non_striker       207881 non-null  object
 10  bowler            207881 non-null  object
 11  runs_off_bat      207881 non-null  int64
 12  extras            207881 non-null  int64
 13  wides             6319 non-null    float64
 14  noballs           842 non-null     float64
 15  byes              545 non-null     float64
 16  legbyes           3280 non-null    float64
 17  wicket_type       10212 non-null   object
 18  player_dismissed  10212 non-null   object
dtypes: float64(5), int64(5), object(9)
memory usage: 31.7+ MB

In [115]:
def whole_over(x):
    if str(x)[-1] == '6':
        x = int(x) + 1
    return x

In [117]:
l1 = {}
l2={}
l3={}
l5={}
dummy = [i for i in range(1752)]
wickets_taken = df_filtered[df_filtered['wicket_type'].notna()].index
l6 = dict.fromkeys(dummy, 0)
l7 = dict.fromkeys(dummy, 0)
l8 = {}
l9 = {}
count = 0

for i in range(len(df_filtered['batting_team'])):
    if(i != 207881 and df_filtered.iloc[i, 6] == df_filtered.iloc[i+1, 6]):
        l1[count] = df_filtered['match_id'][i]
        l2[count]=df_filtered['season'][i]
        l3[count]=df_filtered['venue'][i]
        
        l5[count]=df_filtered['batting_team'][i]
        l6[count] = l6[count] + df_filtered['runs_off_bat'][i] + df_filtered['extras'][i]
        if i in wickets_taken:
            l7[count] += 1
    else:
        l8[count] = (df_filtered['ball'][i])
        l8[count] = whole_over(l8[count])
        l9[count] = l6[count]/ l8[count]
        count += 1

KeyError: 15417

In [48]:
team_metric['match_id'] = list(l1.values())
team_metric['season'] = list(l2.values())
team_metric['venue'] = list(l3.values())
team_metric['batting_team'] = list(l5.values())
team_metric['total_score'] = list(l6.values())
team_metric['wickets'] = list(l7.values())
team_metric['end_over'] = list(l8.values())
team_metric['arr'] = list(l9.values())

In [49]:
team_metric

,match_id,season,venue,batting_team,total_score,wickets,end_over,arr
0,335982,2008,M Chinnaswamy Stadium,Kolkata Knight Riders,216,3,20.0,10.800000
1,335982,2008,M Chinnaswamy Stadium,Royal Challengers Bangalore,82,9,15.2,5.394737
2,335983,2008,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,238,5,20.0,11.900000
3,335983,2008,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,207,4,20.0,10.350000
4,335984,2008,Feroz Shah Kotla,Rajasthan Royals,129,8,20.0,6.450000
...,...,...,...,...,...,...,...,...
1747,1254115,2021,Sharjah Cricket Stadium,Kolkata Knight Riders,138,6,19.4,7.113402
1748,1254116,2021,Sharjah Cricket Stadium,Delhi Capitals,129,5,20.0,6.450000
1749,1254116,2021,Sharjah Cricket Stadium,Kolkata Knight Riders,130,7,19.5,6.666667
1750,1254117,2021,Dubai International Cricket Stadium,Chennai Super Kings,192,2,20.0,9.600000
1751,1254117,2021,Dubai International Cricket Stadium,Kolkata Knight Riders,164,9,20.0,8.200000

In [50]:
team_metric.describe()

,match_id,season,total_score,wickets,end_over,arr
count,1.752000e+03,1752.000000,1752.000000,1752.000000,1752.000000,1752.000000
mean,7.919921e+05,2014.433219,152.897260,5.638699,18.726142,10.337320
std,3.210500e+05,3.966031,35.640901,2.432445,3.146973,26.917965
min,3.359820e+05,2008.000000,1.000000,0.000000,0.300000,1.818182
25%,5.012438e+05,2011.000000,134.000000,4.000000,19.100000,7.076698
50%,7.340120e+05,2014.000000,155.000000,6.000000,19.800000,8.070621
75%,1.136584e+06,2018.000000,173.000000,8.000000,20.000000,9.050000
max,1.254117e+06,2021.000000,371.000000,19.000000,20.000000,550.000000

In [54]:
team_metric[team_metric['end_over']==0.3]

,match_id,season,venue,batting_team,total_score,wickets,end_over,arr
1490,1178426,2019,Wankhede Stadium,Mumbai Indians,7,0,0.3,23.333333
1511,1216493,2020,Dubai International Cricket Stadium,Kings XI Punjab,159,9,0.3,530.000000
1512,1216493,2020,Dubai International Cricket Stadium,Delhi Capitals,1,0,0.3,3.333333
1579,1216512,2020,Sheikh Zayed Stadium,Sunrisers Hyderabad,165,7,0.3,550.000000

In [53]:
df[df['match_id']==1216512]

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wides,noballs,byes,legbyes,wicket_type,player_dismissed
187447,1216512,2020,2020-10-18,Sheikh Zayed Stadium,1,0.1,Kolkata Knight Riders,Sunrisers Hyderabad,Shubman Gill,RA Tripathi,Sandeep Sharma,0,0,NaN,NaN,NaN,NaN,NaN,NaN
187448,1216512,2020,2020-10-18,Sheikh Zayed Stadium,1,0.2,Kolkata Knight Riders,Sunrisers Hyderabad,Shubman Gill,RA Tripathi,Sandeep Sharma,1,0,NaN,NaN,NaN,NaN,NaN,NaN
187449,1216512,2020,2020-10-18,Sheikh Zayed Stadium,1,0.3,Kolkata Knight Riders,Sunrisers Hyderabad,RA Tripathi,Shubman Gill,Sandeep Sharma,4,0,NaN,NaN,NaN,NaN,NaN,NaN
187450,1216512,2020,2020-10-18,Sheikh Zayed Stadium,1,0.4,Kolkata Knight Riders,Sunrisers Hyderabad,RA Tripathi,Shubman Gill,Sandeep Sharma,0,0,NaN,NaN,NaN,NaN,NaN,NaN
187451,1216512,2020,2020-10-18,Sheikh Zayed Stadium,1,0.5,Kolkata Knight Riders,Sunrisers Hyderabad,RA Tripathi,Shubman Gill,Sandeep Sharma,1,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187693,1216512,2020,2020-10-18,Sheikh Zayed Stadium,3,0.3,Sunrisers Hyderabad,Kolkata Knight Riders,Abdul Samad,JM Bairstow,LH Ferguson,0,0,NaN,NaN,NaN,NaN,bowled,Abdul Samad
187694,1216512,2020,2020-10-18,Sheikh Zayed Stadium,4,0.1,Kolkata Knight Riders,Sunrisers Hyderabad,EJG Morgan,KD Karthik,Rashid Khan,0,0,NaN,NaN,NaN,NaN,NaN,NaN
187695,1216512,2020,2020-10-18,Sheikh Zayed Stadium,4,0.2,Kolkata Knight Riders,Sunrisers Hyderabad,EJG Morgan,KD Karthik,Rashid Khan,1,0,NaN,NaN,NaN,NaN,NaN,NaN
187696,1216512,2020,2020-10-18,Sheikh Zayed Stadium,4,0.3,Kolkata Knight Riders,Sunrisers Hyderabad,KD Karthik,EJG Morgan,Rashid Khan,0,0,NaN,NaN,NaN,NaN,NaN,NaN
187697,1216512,2020,2020-10-18,Sheikh Zayed Stadium,4,0.4,Kolkata Knight Riders,Sunrisers Hyderabad,KD Karthik,EJG Morgan,Rashid Khan,0,2,NaN,NaN,NaN,2.0,NaN,NaN

In [55]:
df.loc[(df['match_id']==1178426)]

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wides,noballs,byes,legbyes,wicket_type,player_dismissed
176666,1178426,2019,2019-05-02,Wankhede Stadium,1,0.1,Mumbai Indians,Sunrisers Hyderabad,RG Sharma,Q de Kock,B Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN
176667,1178426,2019,2019-05-02,Wankhede Stadium,1,0.2,Mumbai Indians,Sunrisers Hyderabad,RG Sharma,Q de Kock,B Kumar,4,0,NaN,NaN,NaN,NaN,NaN,NaN
176668,1178426,2019,2019-05-02,Wankhede Stadium,1,0.3,Mumbai Indians,Sunrisers Hyderabad,RG Sharma,Q de Kock,B Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN
176669,1178426,2019,2019-05-02,Wankhede Stadium,1,0.4,Mumbai Indians,Sunrisers Hyderabad,RG Sharma,Q de Kock,B Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN
176670,1178426,2019,2019-05-02,Wankhede Stadium,1,0.5,Mumbai Indians,Sunrisers Hyderabad,RG Sharma,Q de Kock,B Kumar,0,1,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176912,1178426,2019,2019-05-02,Wankhede Stadium,3,0.3,Sunrisers Hyderabad,Mumbai Indians,Mohammad Nabi,MJ Guptill,JJ Bumrah,6,0,NaN,NaN,NaN,NaN,NaN,NaN
176913,1178426,2019,2019-05-02,Wankhede Stadium,3,0.4,Sunrisers Hyderabad,Mumbai Indians,Mohammad Nabi,MJ Guptill,JJ Bumrah,0,0,NaN,NaN,NaN,NaN,bowled,Mohammad Nabi
176914,1178426,2019,2019-05-02,Wankhede Stadium,4,0.1,Mumbai Indians,Sunrisers Hyderabad,HH Pandya,KA Pollard,Rashid Khan,6,0,NaN,NaN,NaN,NaN,NaN,NaN
176915,1178426,2019,2019-05-02,Wankhede Stadium,4,0.2,Mumbai Indians,Sunrisers Hyderabad,HH Pandya,KA Pollard,Rashid Khan,1,0,NaN,NaN,NaN,NaN,NaN,NaN
176916,1178426,2019,2019-05-02,Wankhede Stadium,4,0.3,Mumbai Indians,Sunrisers Hyderabad,KA Pollard,HH Pandya,Rashid Khan,2,0,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
team_metric.iloc[1489,:]

match_id                    1178426
season                         2019
venue              Wankhede Stadium
batting_team    Sunrisers Hyderabad
total_score                     170
wickets                           7
end_over                        0.4
arr                           425.0
Name: 1489, dtype: object